#
#
#

title: '分析服务器配置修改'

# 表单项
formItems: [
  {
      type: 'string',
      label: 'MySQL IP',
      name: 'dbHost',
      value: '127.0.0.1',
      placeholder: '',
  },
  {
      type: 'number',
      label: 'MySQL 端口',
      name: 'dbPort',
      value: 3306,
      placeholder: '',
  },
  {
      type: 'string',
      label: '数据库',
      name: 'dbSchema',
      value: 'mymonitor',
      placeholder: '',
  },
  {
      type: 'string',
      label: '数据库账号',
      name: 'dbUser',
      value: 'mmt_app',
      placeholder: '',
  },
  {
      type: 'string',
      label: '数据库密码',
      name: 'dbPassword',
      value: 'poms@db',
      placeholder: '',
  },
  {
      type: 'string',
      label: 'Solr IP',
      name: 'solrHost',
      value: '127.0.0.1',
      placeholder: '',
  },
  {
      type: 'number',
      label: 'Solr 端口',
      name: 'solrPort',
      value: 8081,
      placeholder: '',
      helpText: '该端口是 Tomcat 监听的端口，如果 Tomcat 端口更改，此处也要修改',
  },
  {
      type: 'string',
      label: '重新分类地址',
      name: 'reclassifyUrl',
      value: 'http://192.168.1.10:80/kwm_subject_classifier',
      placeholder: '',
      helpText: '重新分类调用的地址',
  },
]


# 模板配置
# {
#   name: '',       # 名称
#   desc: '',       # 详细描述
#   templateFile: '',   # 模板路径（相对路径）
#   dest: '',       # 目标路径，生成新内容之后存放的路径
# },
# 注意，name 不能一样
templates: [
  {
    name: '1_Configure.php',
    desc: 'KWM2017 配置文件',
    templateFile: 'kwm-configure.php',
    dest: 'D:\KWM\Application_Server\www_root\kwm\server\app\lib\Config\Configure.php',
  },
  {
    name: '2_Configure.php',
    desc: 'KWMCloud 配置文件',
    templateFile: 'cloud-configure.php',
    dest: 'D:\KWM\Application_Server\www_root\kwmcloud\server\app\lib\Config\Configure.php',
  },
]
