#
#
#

title: ''

# 表单项
formItems: [

]


# 模板配置
# {
#   name: '',       # 名称
#   desc: '',       # 详细描述
#   templateFile: '',   # 模板路径（相对路径）
#   dest: '',       # 目标路径，生成新内容之后存放的路径
# },
templates: [

]
